apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dev-ml-api-adapter-service
  namespace: mojaloop
  annotations:
    kubernetes.io/ingress.global-static-ip-name: helloweb-ip
spec:
  rules:
  - host: dev-ml-api-adapter-service.red2.demo.openafrica.network
    http:
      paths:
      - backend:
          serviceName: dev-ml-api-adapter-service
          servicePort: 3000
        path: /
