apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dev-centralledger-handler-admin-transfer
  annotations:
    kubernetes.io/ingress.global-static-ip-name: helloweb-ip
spec:
  rules:
  - host: central-ledger-admin-transfer.red1.demo.openafrica.network
    http:
      paths:
      - backend:
          serviceName: dev-centralledger-handler-admin-transfer
          servicePort: 3000
        path: /
---
apiVersion: v1
kind: Service
metadata:
  name: dev-centralledger-handler-admin-transfer
spec:
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dev-centralledger-handler-timeout
  annotations:
    kubernetes.io/ingress.global-static-ip-name: helloweb-ip
spec:
  rules:
  - host: central-ledger-timeout.red1.demo.openafrica.network
    http:
      paths:
      - backend:
          serviceName: dev-centralledger-handler-timeout
          servicePort: 3000
        path: /
---
apiVersion: v1
kind: Service
metadata:
  name: dev-centralledger-handler-timeout
spec:
  type: NodePort
