apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  creationTimestamp: 2019-01-16T12:42:17Z
  generation: 1
  labels:
    app: dev-centralledger-handler-admin-transfer
    chart: centralledger-handler-admin-transfer-4.3.0
    heritage: Tiller
    release: dev
  name: dev-centralledger-handler-admin-transfer
  namespace: mojaloop
  resourceVersion: "364452"
  selfLink: /apis/extensions/v1beta1/namespaces/mojaloop/ingresses/dev-centralledger-handler-admin-transfer
  uid: 28ab3fab-198c-11e9-afa0-42010a8001e4
spec:
  rules:
  - host: central-ledger-admin-transfer.red.demo.openafrica.network
    http:
      paths:
      - backend:
          serviceName: dev-centralledger-handler-admin-transfer
          servicePort: 3000
        path: /
status:
  loadBalancer:
    ingress:
    - ip: 10.128.0.37

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  creationTimestamp: 2019-01-16T12:42:18Z
  generation: 1
  labels:
    app: dev-centralledger-handler-timeout
    chart: centralledger-handler-timeout-4.3.0
    heritage: Tiller
    release: dev
  name: dev-centralledger-handler-timeout
  namespace: mojaloop
  resourceVersion: "364444"
  selfLink: /apis/extensions/v1beta1/namespaces/mojaloop/ingresses/dev-centralledger-handler-timeout
  uid: 28b05c36-198c-11e9-afa0-42010a8001e4
spec:
  rules:
  - host: central-ledger-timeout.red.demo.openafrica.network
    http:
      paths:
      - backend:
          serviceName: dev-centralledger-handler-timeout
          servicePort: 3000
        path: /
status:
  loadBalancer:
    ingress:
    - ip: 10.128.0.37

