apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dev-centraldirectory
  namespace: mojaloop
  annotations:
    kubernetes.io/ingress.global-static-ip-name: za.blue.demo.openafrica.network
spec:
  rules:
  - host: dev-centraldirectory.za.blue.demo.openafrica.network
    http:
      paths:
      - backend:
          serviceName: dev-centraldirectory
          servicePort: 3000
        path: /

---
apiVersion: v1
kind: Service
metadata:
  name: dev-centraldirectory
  namespace: mojaloop
spec:
  type: NodePort
  ports:
  - port: 3000
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dev-centraleventprocessor
  namespace: mojaloop
  annotations:
    kubernetes.io/ingress.global-static-ip-name: za.blue.demo.openafrica.network
spec:
  rules:
  - host: dev-centraleventprocessor.za.blue.demo.openafrica.network
    http:
      paths:
      - backend:
          serviceName: dev-centraleventprocessor
          servicePort: http
        path: /
---
apiVersion: v1
kind: Service
metadata:
  name: dev-centraleventprocessor
  namespace: mojaloop
spec:
  type: NodePort
  ports:
  - port: 3080
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dev-centralkms
  namespace: mojaloop
  annotations:
    kubernetes.io/ingress.global-static-ip-name: za.blue.demo.openafrica.network
spec:
  rules:
  - host: dev-centralkms.za.blue.demo.openafrica.network
    http:
      paths:
      - backend:
          serviceName: dev-centralkms
          servicePort: 8080
        path: /
---
apiVersion: v1
kind: Service
metadata:
  name: dev-centralkms
  namespace: mojaloop
spec:
  type: NodePort
  ports:
  - port: 8080
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dev-centralledger-handler-admin-transfer
  namespace: mojaloop
  annotations:
    kubernetes.io/ingress.global-static-ip-name: za.blue.demo.openafrica.network
spec:
  rules:
  - host: dev-centralledger-handler-admin-transfer.za.blue.demo.openafrica.network
    http:
      paths:
      - backend:
          serviceName: dev-centralledger-handler-admin-transfer
          servicePort: 3000
        path: /
---
apiVersion: v1
kind: Service
metadata:
  name: dev-centralledger-handler-admin-transfer
  namespace: mojaloop
spec:
  type: NodePort
  ports:
  - port: 3000
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dev-centralledger-handler-timeout
  namespace: mojaloop
  annotations:
    kubernetes.io/ingress.global-static-ip-name: za.blue.demo.openafrica.network
spec:
  rules:
  - host: dev-centralledger-handler-timeout.za.blue.demo.openafrica.network
    http:
      paths:
      - backend:
          serviceName: dev-centralledger-handler-timeout
          servicePort: 3000
        path: /
---
apiVersion: v1
kind: Service
metadata:
  name: dev-centralledger-handler-timeout
  namespace: mojaloop
spec:
  type: NodePort
  ports:
  - port: 3000
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dev-centralledger-handler-transfer-fulfil
  namespace: mojaloop
  annotations:
    kubernetes.io/ingress.global-static-ip-name: za.blue.demo.openafrica.network
spec:
  rules:
  - host: dev-centralledger-handler-transfer-fulfil.za.blue.demo.openafrica.network
    http:
      paths:
      - backend:
          serviceName: dev-centralledger-handler-transfer-fulfil
          servicePort: 3000
        path: /
---
apiVersion: v1
kind: Service
metadata:
  name: dev-centralledger-handler-transfer-fulfil
  namespace: mojaloop
spec:
  type: NodePort
  ports:
  - port: 3000
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dev-centralledger-handler-transfer-get
  namespace: mojaloop
  annotations:
    kubernetes.io/ingress.global-static-ip-name: za.blue.demo.openafrica.network
spec:
  rules:
  - host: dev-centralledger-handler-transfer-get.za.blue.demo.openafrica.network
    http:
      paths:
      - backend:
          serviceName: dev-centralledger-handler-transfer-get
          servicePort: 3000
        path: /
---
apiVersion: v1
kind: Service
metadata:
  name: dev-centralledger-handler-transfer-get
  namespace: mojaloop
spec:
  type: NodePort
  ports:
  - port: 3000
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dev-centralledger-handler-transfer-position
  namespace: mojaloop
  annotations:
    kubernetes.io/ingress.global-static-ip-name: za.blue.demo.openafrica.network
spec:
  rules:
  - host: dev-centralledger-handler-transfer-position.za.blue.demo.openafrica.network
    http:
      paths:
      - backend:
          serviceName: dev-centralledger-handler-transfer-position
          servicePort: 3000
        path: /
---
apiVersion: v1
kind: Service
metadata:
  name: dev-centralledger-handler-transfer-position
  namespace: mojaloop
spec:
  type: NodePort
  ports:
  - port: 3000
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dev-centralledger-handler-transfer-prepare
  namespace: mojaloop
  annotations:
    kubernetes.io/ingress.global-static-ip-name: za.blue.demo.openafrica.network
spec:
  rules:
  - host: dev-centralledger-handler-transfer-prepare.za.blue.demo.openafrica.network
    http:
      paths:
      - backend:
          serviceName: dev-centralledger-handler-transfer-prepare
          servicePort: 3000
        path: /
---
apiVersion: v1
kind: Service
metadata:
  name: dev-centralledger-handler-transfer-prepare
  namespace: mojaloop
spec:
  type: NodePort
  ports:
  - port: 3000
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dev-centralledger-service
  namespace: mojaloop
  annotations:
    kubernetes.io/ingress.global-static-ip-name: za.blue.demo.openafrica.network
spec:
  rules:
  - host: dev-centralledger-service.za.blue.demo.openafrica.network
    http:
      paths:
      - backend:
          serviceName: dev-centralledger-service
          servicePort: 3000
        path: /
  - host: dev-centralledger-service.za.blue.demo.openafrica.network
    http:
      paths:
      - backend:
          serviceName: dev-centralledger-service
          servicePort: 3001
        path: /admin
---
apiVersion: v1
kind: Service
metadata:
  name: dev-centralledger-service
  namespace: mojaloop
spec:
  type: NodePort
  ports:
  - name: http-api
    port: 3000
  - name: http-api-admin
    port: 3001
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dev-centralsettlement
  namespace: mojaloop
  annotations:
    kubernetes.io/ingress.global-static-ip-name: za.blue.demo.openafrica.network
spec:
  rules:
  - host: dev-centralsettlement.za.blue.demo.openafrica.network
    http:
      paths:
      - backend:
          serviceName: dev-centralsettlement
          servicePort: 3007
        path: /
---
apiVersion: v1
kind: Service
metadata:
  name: dev-centralsettlement
  namespace: mojaloop
spec:
  type: NodePort
  ports:
  - port: 3007
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dev-emailnotifier
  namespace: mojaloop
  annotations:
    kubernetes.io/ingress.global-static-ip-name: za.blue.demo.openafrica.network
spec:
  rules:
  - host: dev-emailnotifier.za.blue.demo.openafrica.network
    http:
      paths:
      - backend:
          serviceName: dev-emailnotifier
          servicePort: http
        path: /
---
apiVersion: v1
kind: Service
metadata:
  name: dev-emailnotifier
  namespace: mojaloop
spec:
  type: NodePort
  ports:
  - port: 3081
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dev-interop-switch
  namespace: mojaloop
  annotations:
    kubernetes.io/ingress.global-static-ip-name: za.blue.demo.openafrica.network
spec:
  rules:
  - host: dev-interop-switch.za.blue.demo.openafrica.network
    http:
      paths:
      - backend:
          serviceName: dev-interop-switch
          servicePort: 8088
        path: /
---
apiVersion: v1
kind: Service
metadata:
  name: dev-interop-switch
  namespace: mojaloop
spec:
  type: NodePort
  ports:
  - port: 8088
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dev-ml-api-adapter-handler-notification
  namespace: mojaloop
  annotations:
    kubernetes.io/ingress.global-static-ip-name: za.blue.demo.openafrica.network
spec:
  rules:
  - host: dev-ml-api-adapter-handler-notification.za.blue.demo.openafrica.network
    http:
      paths:
      - backend:
          serviceName: dev-ml-api-adapter-handler-notification
          servicePort: 8088
        path: /
---
apiVersion: v1
kind: Service
metadata:
  name: dev-ml-api-adapter-handler-notification
  namespace: mojaloop
spec:
  type: NodePort
  ports:
  - port: 8088
---
