apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dev-centraldirectory
  namespace: mojaloop
  annotations:
    kubernetes.io/ingress.global-static-ip-name: red.demo.openafrica.network
spec:
  rules:
  - host: dev-centraldirectory.red.demo.openafrica.network
    http:
      paths:
      - backend:
          serviceName: dev-centraldirectory
          servicePort: 3000
        path: /

---
apiVersion: v1
kind: Service
metadata:
  name: dev-centraldirectory
  namespace: mojaloop
spec:
  type: NodePort
  ports:
  - port: 3000
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dev-centraleventprocessor
  namespace: mojaloop
  annotations:
    kubernetes.io/ingress.global-static-ip-name: red.demo.openafrica.network
spec:
  rules:
  - host: dev-centraleventprocessor.red.demo.openafrica.network
    http:
      paths:
      - backend:
          serviceName: dev-centraleventprocessor
          servicePort: 3000
        path: /
--- 
apiVersion: v1
kind: Service
metadata:
  name: dev-centraleventprocessor
  namespace: mojaloop
spec:
  type: NodePort
  ports:
  - port: 3080
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dev-centralkms
  namespace: mojaloop
  annotations:
    kubernetes.io/ingress.global-static-ip-name: red.demo.openafrica.network
spec:
  rules:
  - host: dev-centralkms.red.demo.openafrica.network
    http:
      paths:
      - backend:
          serviceName: dev-centralkms
          servicePort: 3000
        path: /
---
apiVersion: v1
kind: Service
metadata:
  name: dev-centralkms
  namespace: mojaloop
spec:
  type: NodePort
  ports:
  - port: 8080
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dev-centralledger-handler-admin-transfer
  namespace: mojaloop
  annotations:
    kubernetes.io/ingress.global-static-ip-name: red.demo.openafrica.network
spec:
  rules:
  - host: dev-centralledger-handler-admin-transfer.red.demo.openafrica.network
    http:
      paths:
      - backend:
          serviceName: dev-centralledger-handler-admin-transfer
          servicePort: 3000
        path: /
---
apiVersion: v1
kind: Service
metadata:
  name: dev-centralledger-handler-admin-transfer
  namespace: mojaloop
spec:
  type: NodePort
  ports:
  - port: 3000
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dev-centralledger-handler-timeout
  namespace: mojaloop
  annotations:
    kubernetes.io/ingress.global-static-ip-name: red.demo.openafrica.network
spec:
  rules:
  - host: dev-centralledger-handler-timeout.red.demo.openafrica.network
    http:
      paths:
      - backend:
          serviceName: dev-centralledger-handler-timeout
          servicePort: 3000
        path: /
---
apiVersion: v1
kind: Service
metadata:
  name: dev-centralledger-handler-timeout
  namespace: mojaloop
spec:
  type: NodePort
  ports:
  - port: 3000
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dev-centralledger-handler-transfer-fulfil
  namespace: mojaloop
  annotations:
    kubernetes.io/ingress.global-static-ip-name: red.demo.openafrica.network
spec:
  rules:
  - host: dev-centralledger-handler-transfer-fulfil.red.demo.openafrica.network
    http:
      paths:
      - backend:
          serviceName: dev-centralledger-handler-transfer-fulfil
          servicePort: 3000
        path: /
---
apiVersion: v1
kind: Service
metadata:
  name: dev-centralledger-handler-transfer-fulfil
  namespace: mojaloop
spec:
  type: NodePort
  ports:
  - port: 3000
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dev-centralledger-handler-transfer-get
  namespace: mojaloop
  annotations:
    kubernetes.io/ingress.global-static-ip-name: red.demo.openafrica.network
spec:
  rules:
  - host: dev-centralledger-handler-transfer-get.red.demo.openafrica.network
    http:
      paths:
      - backend:
          serviceName: dev-centralledger-handler-transfer-get
          servicePort: 3000
        path: /
---
apiVersion: v1
kind: Service
metadata:
  name: dev-centralledger-handler-transfer-get
  namespace: mojaloop
spec:
  type: NodePort
  ports:
  - port: 3000
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dev-centralledger-handler-transfer-position
  namespace: mojaloop
  annotations:
    kubernetes.io/ingress.global-static-ip-name: red.demo.openafrica.network
spec:
  rules:
  - host: dev-centralledger-handler-transfer-position.red.demo.openafrica.network
    http:
      paths:
      - backend:
          serviceName: dev-centralledger-handler-transfer-position
          servicePort: 3000
        path: /
---
apiVersion: v1
kind: Service
metadata:
  name: dev-centralledger-handler-transfer-position
  namespace: mojaloop
spec:
  type: NodePort
  ports:
  - port: 3000
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dev-centralledger-handler-transfer-prepare
  namespace: mojaloop
  annotations:
    kubernetes.io/ingress.global-static-ip-name: red.demo.openafrica.network
spec:
  rules:
  - host: dev-centralledger-handler-transfer-prepare.red.demo.openafrica.network
    http:
      paths:
      - backend:
          serviceName: dev-centralledger-handler-transfer-prepare
          servicePort: 3000
        path: /
---
apiVersion: v1
kind: Service
metadata:
  name: dev-centralledger-handler-transfer-prepare
  namespace: mojaloop
spec:
  type: NodePort
  ports:
  - port: 3000
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dev-centralledger-service
  namespace: mojaloop
  annotations:
    kubernetes.io/ingress.global-static-ip-name: red.demo.openafrica.network
spec:
  rules:
  - host: dev-centralledger-service.red.demo.openafrica.network
    http:
      paths:
      - backend:
          serviceName: dev-centralledger-service
          servicePort: 3000
        path: /
  - host: dev-centralledger-service.red.demo.openafrica.network
    http:
      paths:
      - backend:
          serviceName: dev-centralledger-service
          servicePort: 3001
        path: /admin
--- 
apiVersion: v1
kind: Service
metadata:
  name: dev-centralledger-service
  namespace: mojaloop
spec:
  type: NodePort
  ports:
  - port: 3080
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dev-centralsettlement
  namespace: mojaloop
  annotations:
    kubernetes.io/ingress.global-static-ip-name: red.demo.openafrica.network
spec:
  rules:
  - host: dev-centralsettlement.red.demo.openafrica.network
    http:
      paths:
      - backend:
          serviceName: dev-centralsettlement
          servicePort: 3000
        path: /
---
apiVersion: v1
kind: Service
metadata:
  name: dev-centralsettlement
  namespace: mojaloop
spec:
  type: NodePort
  ports:
  - port: 3000
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dev-emailnotifier
  namespace: mojaloop
  annotations:
    kubernetes.io/ingress.global-static-ip-name: red.demo.openafrica.network
spec:
  rules:
  - host: dev-emailnotifier.red.demo.openafrica.network
    http:
      paths:
      - backend:
          serviceName: dev-emailnotifier
          servicePort: 3000
        path: /
---
apiVersion: v1
kind: Service
metadata:
  name: dev-emailnotifier
  namespace: mojaloop
spec:
  type: NodePort
  ports:
  - port: 3000
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dev-interop-switch
  namespace: mojaloop
  annotations:
    kubernetes.io/ingress.global-static-ip-name: red.demo.openafrica.network
spec:
  rules:
  - host: dev-interop-switch.red.demo.openafrica.network
    http:
      paths:
      - backend:
          serviceName: dev-interop-switch
          servicePort: 3000
        path: /
---
apiVersion: v1
kind: Service
metadata:
  name: dev-interop-switch
  namespace: mojaloop
spec:
  type: NodePort
  ports:
  - port: 3000
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dev-ml-api-adapter-handler-notification
  namespace: mojaloop
  annotations:
    kubernetes.io/ingress.global-static-ip-name: red.demo.openafrica.network
spec:
  rules:
  - host: dev-ml-api-adapter-handler-notification.red.demo.openafrica.network
    http:
      paths:
      - backend:
          serviceName: dev-ml-api-adapter-handler-notification
          servicePort: 3000
        path: /
---
apiVersion: v1
kind: Service
metadata:
  name: dev-ml-api-adapter-handler-notification
  namespace: mojaloop
spec:
  type: NodePort
  ports:
  - port: 3000
---
