apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dev-centraldirectory
  namespace: mojaloop
  annotations:
    kubernetes.io/ingress.global-static-ip-name: red3.demo.openafrica.network
spec:
  rules:
  - host: dev-centraldirectory.red3.demo.openafrica.network
    http:
      paths:
      - backend:
          serviceName: dev-centraldirectory
          servicePort: 3000
        path: /

---
apiVersion: v1
kind: Service
metadata:
  name: dev-centraldirectory
spec:
  ports:
    port: 3000
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dev-centraleventprocessor
  namespace: mojaloop
  annotations:
    kubernetes.io/ingress.global-static-ip-name: red3.demo.openafrica.network
spec:
  rules:
  - host: dev-centraleventprocessor.red2.demo.openafrica.network
    http:
      paths:
      - backend:
          serviceName: dev-centraleventprocessor
          servicePort: 3000
        path: /
---
apiVersion: v1
kind: Service
metadata:
  name: dev-centraleventprocessor
spec:
  ports: 
    port: 3000
  type: NodePort
---
