apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dev-centraldirectory
  namespace: mojaloop
  annotations:
    kubernetes.io/ingress.global-static-ip-name: nr.demo.openafrica.network
spec:
  rules:
  - host: dev-centraldirectory.nr.demo.openafrica.network
    http:
      paths:
      - backend:
          serviceName: dev-centraldirectory
          servicePort: 3000
        path: /

---
apiVersion: v1
kind: Service
metadata:
  name: dev-centraldirectory
spec:
  type: NodePort
  ports:
  - port: 8080
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dev-centraleventprocessor
  namespace: mojaloop
  annotations:
    kubernetes.io/ingress.global-static-ip-name: nr.demo.openafrica.network
spec:
  rules:
  - host: dev-centraleventprocessor.nr.demo.openafrica.network
    http:
      paths:
      - backend:
          serviceName: dev-centraleventprocessor
          servicePort: 3000
        path: /
---
apiVersion: v1
kind: Service
metadata:
  name: dev-centraleventprocessor
spec:
  type: NodePort
  ports:
  - port: 3080
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dev-centralkms
  namespace: mojaloop
  annotations:
    kubernetes.io/ingress.global-static-ip-name: nr.demo.openafrica.network
spec:
  rules:
  - host: dev-centralkms.nr.demo.openafrica.network
    http:
      paths:
      - backend:
          serviceName: dev-centralkms
          servicePort: 3000
        path: /
---
apiVersion: v1
kind: Service
metadata:
  name: dev-centralkms
spec:
  type: NodePort
  ports:
  - port: 8080
---
